apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-app
  namespace: infra-tools
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: ml-platform
    environment: dev
spec:
  project: default
  source:
    repoURL: "https://gitlab.com/polishchuk500-group/goit-homework-templates.git"
    path: application
    targetRevision: lesson-7
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
  labels:
    name: mlflow

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.8.1
        ports:
        - containerPort: 5000
        command:
          - mlflow
          - server
          - --host=0.0.0.0
          - --port=5000
          - --backend-store-uri=sqlite:///tmp/mlflow.db
          - --default-artifact-root=/tmp/artifacts
          - --serve-artifacts
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: ""
        volumeMounts:
        - name: mlflow-data
          mountPath: /mlflow-data
      volumes:
      - name: mlflow-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: mlflow
  labels:
    app: mlflow
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: mlflow

