apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  source:
    repoURL: git@github.com:LesyaTkachuk/mlflow-infra.git
    targetRevision: master
    path: infra/mlflow
    helm:
      releaseName: mlflow
      valueFiles:
        - my-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
