apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: cluster-addons
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    chart: kube-prometheus-stack
    targetRevision: 77.0.2
    helm:
      valueObjects:
        grafana:
          ingress:
            enabled: false
        prometheus:
          ingress:
            enabled: false
        alertmanager:
          enabled: false
        prometheusOperator:
          createCustomResource: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
